### ISSUE TITLE
未能找到联系方式，于是到这里来提问了

### ISSUE THREAD

**Issue by EricLingRui** [zhpmatrix/CGED_TF#1]
很荣幸在研究CGED的时候，能看到您正在为其代码复现。我有一个很广义的问题：目前，句法分析、语义分析是基于文本本身语法规则正确的情况下适用，若一段长文本（特定领域）中存在大量的语法错误（人还是能读懂的），机器难以通过句法分析、语义分析来进行更深层的工作，比如关系抽取、语义依存等。在这种情况下，您觉得采用什么样的策略能得以解决？
    我的思路有两种：1、通过分句，将长文化短句，经过零指代消解等将短句结构补充完整，再进行CGED，最后做依存等基于正确语法规则的特征获取工作。2、就这些错误语法比较多的文本，只采取词法分析的特征做关系抽取等工作，这个就要求新模型的研究了。并且已验证过这些文本在词法分析上是没有问题的。
    思路1拆句的原因是在读完哈工讯飞联合实验室最新的那篇《Chinese Grammatical Error Diagnosis using Statistical and Prior Knowledge driven Features with Probabilistic Ensemble Enhancement》论文后，感觉它也只能简单解决一些小语法错误。
    下面我举一个例子：张凌瑞回到其位于本县的家中换鞋后，看见一陌生年轻男子左手挡脸右手持剪刀从自己卧室出来走到自己面前，用剪刀指着自己胸口说没有偷东西并要求曾丽萍让开后逃逸。
    例子存在多个零指代，且有语法错误，像这样的句子，如何信息结果化，望提出宝贵建议！谢谢。

**Comment by zhpmatrix** [comment]
@EricLingRui 
我复现的是ACL2017年的SOTA，也是HIT的。你提出了一个很广义且很重要的问题。针对这个问题，我有一些比较民科的看法。第一，语法错误和不错误是一个相对的概念，语言是文化的产物，没有绝对的事实正确和事实错误的区分，起码对机器而言是这样的。第二，你确定机器读懂了自然语言？这里可能需要思考“读懂”的含义。

针对你的解决思路，第一个是修正语法后，获得合法输入，然后接入目前NLP的研究路线；第二个是直接将错误语法的文本当做合法输入进行研究。其实第二个思路和我上述的一些看法是一致，这个取决于我们的任务目的是什么？比如CGED的训练数据是有标注的，且这个标注是参照现行合法语法体系的。对于一个supervised learning问题，相当于定义好了input/output, 测试时给定input得到output，不必关心output=f(input)中的f是什么？而这个f某种意义上定义了合法和非法的分类边界。

ACL2018的SOTA我浏览了一下文章，感觉Trick较多，稍后要不要复现，看组里是否有需求吧。CGED的问题我一直觉得很复杂，包括自己最近做数据增强，构造数据，其实引入了相当多的noise，给指代消解带来的问题是表现之一吧。

欢迎交流。
