### ISSUE TITLE
你好，请问可以共享一下你这个代码的数据或者数据格式吗？

### ISSUE THREAD

**Issue by xiaoxiaoAurora** [zhpmatrix/CGED_TF#3]
最近我也在尝试复现这篇论文，在看你的代码时发现 get_dicts('data/input/merge_seq.txt', 'data/', 'dict.pkl')这一行 中的  数据文件夹和文件都没有找到，方便提供一份数据吗？ 感谢！uliuxiao@163.c

**Comment by zhpmatrix** [comment]
@xiaoxiaoAurora

Hi，这个代码的数据我应该已经找不到了。不过我给你发一份更棒的数据，CGED从2014年到2018年的所有数据，整理出这份集合似乎并不容易。预处理的流程也应该不太繁琐。

**Comment by xiaoxiaoAurora** [comment]
> @xiaoxiaoAurora
> 
> Hi，这个代码的数据我应该已经找不到了。不过我给你发一份更棒的数据，CGED从2014年到2018年的所有数据，整理出这份集合似乎并不容易。预处理的流程也应该不太繁琐。

好的，非常感谢！还有一个小问题，你还记得数据的格式吗？是和官方公布的数据格式一样，xml吗? 因为在看的过程中我有些地方看不懂，想对照着你的数据格式查看一下。

**Comment by zhpmatrix** [comment]
> > @xiaoxiaoAurora
> > Hi，这个代码的数据我应该已经找不到了。不过我给你发一份更棒的数据，CGED从2014年到2018年的所有数据，整理出这份集合似乎并不容易。预处理的流程也应该不太繁琐。
> 
> 好的，非常感谢！还有一个小问题，你还记得数据的格式吗？是和官方公布的数据格式一样，xml吗? 因为在看的过程中我有些地方看不懂，想对照着你的数据格式查看一下。

好像是如下格式(给定一个句子)：

char0&pos0&tag0  char1&pos1&tag1 ...... charN&posN&tagN

但是我觉得什么格式取决于自己的需要吧。另外，这个代码是备份用的，严格上不算是开源代码，所以代码显得比较乱。抱歉...

**Comment by tzuwei93** [comment]
你好 @zhpmatrix，
最近也在搞CGED，看了你的代码，也可以发一份数据给我吗？感谢~！fivejthree@outlook.com
另外，还有一个小问题，我在看CGED'2018的时候，涉及到了纠正文法错误的任务，但是在官网上没有找到对应的评测代码（只有找到前几年的评测代码），不知道你有找到吗？

感谢！

**Comment by zhpmatrix** [comment]
@tzuw 

Hi, 数据已发送，可以Check下。

我做这个事情的时候，不太关心纠错的事情，所以没有过多的关注。个人认为，单说刷这个数据集是有意义的，但是距离实用还差很远，所以之后就没有沿着这个思路去做。个人觉得可以用一下BERT，结合其他方法去尝试一下，我前段时间做了简单测试，有效果的。

欢迎思路上的交流讨论。

**Comment by tzuwei93** [comment]
> @tzuw
> 
> Hi, 数据已发送，可以Check下。
> 
> 我做这个事情的时候，不太关心纠错的事情，所以没有过多的关注。个人认为，单说刷这个数据集是有意义的，但是距离实用还差很远，所以之后就没有沿着这个思路去做。个人觉得可以用一下BERT，结合其他方法去尝试一下，我前段时间做了简单测试，有效果的。
> 
> 欢迎思路上的交流讨论。

@zhpmatrix 
收到，我尝试看看~！
感谢！

**Comment by loserdog-err** [comment]
@zhpmatrix 
hi ,请问数据还能找到吗，能否发一份给我，感谢。 2313570516@qq.com

**Comment by macanv** [comment]
@zhpmatrix  您好，请问可以发一下上述的数据么，感谢~

**Comment by macanv** [comment]
@zhpmatrix  ma_cancan@163.com, 感谢啊。
